steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean install sonar:sonar']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/KiranTest', '.']
images: ['gcr.io/$PROJECT_ID/KiranTest']
